name: Transifex Integration

on:
  push:
  branches:
    - main
    types: [labeled]

jobs:
  transifex_integration:
    if: github.event.label.name == 'Ready for translations'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Transifex CLI
        run: pip install transifex-client

      - name: "Pull from transifex and commit to the PR"
        with: # Or as an environment variable
            tx_token: ${{ secrets.TX_TOKEN }}
            git_flow: true
            github_token: ${{ secrets.GITHUB_TOKEN }}
            translations_folder: config/locale
            pull_translations: true
            pull_sources: true
            commit_to_pr: true